import { IntegrationWidget, IntegrationType } from '../types/integrations';

export const integrationWidgets: IntegrationWidget[] = [
  {
    type: IntegrationType.TOAST,
    title: 'Toast POS',
    description: 'Connect your Toast POS system to sync orders and menu data',
    iconName: 'restaurant',
    iconColor: '#FF6900',
    fields: [
      {
        key: 'name',
        label: 'Integration Name',
        placeholder: 'e.g., Main Restaurant Toast',
        type: 'text',
        required: true,
        helperText: 'A friendly name to identify this integration',
      },
      {
        key: 'apiKey',
        label: 'API Key',
        placeholder: 'Enter your Toast API key',
        type: 'password',
        required: true,
        helperText: 'Found in Toast Web under API Settings',
      },
      {
        key: 'restaurantGuid',
        label: 'Restaurant GUID',
        placeholder: 'Enter your restaurant GUID',
        type: 'text',
        required: true,
        helperText: 'Your unique Toast restaurant identifier',
      },
      {
        key: 'environment',
        label: 'Environment',
        placeholder: 'Select environment',
        type: 'select',
        required: true,
        options: [
          { label: 'Production', value: 'production' },
          { label: 'Sandbox', value: 'sandbox' },
        ],
      },
    ],
  },
  {
    type: IntegrationType.OPENTABLE,
    title: 'OpenTable',
    description: 'Sync reservation data and guest information from OpenTable',
    iconName: 'book-online',
    iconColor: '#DA3743',
    fields: [
      {
        key: 'name',
        label: 'Integration Name',
        placeholder: 'e.g., Main Restaurant OpenTable',
        type: 'text',
        required: true,
        helperText: 'A friendly name to identify this integration',
      },
      {
        key: 'clientId',
        label: 'Client ID',
        placeholder: 'Enter your OpenTable Client ID',
        type: 'text',
        required: true,
        helperText: 'Provided by OpenTable for API access',
      },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        placeholder: 'Enter your OpenTable Client Secret',
        type: 'password',
        required: true,
        helperText: 'Keep this secure - do not share',
      },
      {
        key: 'restaurantId',
        label: 'Restaurant ID',
        placeholder: 'Enter your Restaurant ID',
        type: 'text',
        required: true,
        helperText: 'Your OpenTable restaurant identifier',
      },
    ],
  },
  {
    type: IntegrationType.QUICKBOOKS,
    title: 'QuickBooks Online',
    description: 'Import financial data and sync accounting information',
    iconName: 'account-balance',
    iconColor: '#2CA01C',
    fields: [
      {
        key: 'name',
        label: 'Integration Name',
        placeholder: 'e.g., Company QuickBooks',
        type: 'text',
        required: true,
        helperText: 'A friendly name to identify this integration',
      },
      {
        key: 'clientId',
        label: 'Client ID',
        placeholder: 'Enter your QuickBooks App Client ID',
        type: 'text',
        required: true,
        helperText: 'From your QuickBooks App dashboard',
      },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        placeholder: 'Enter your QuickBooks App Client Secret',
        type: 'password',
        required: true,
        helperText: 'Keep this secure - do not share',
      },
      {
        key: 'realmId',
        label: 'Company ID (Realm ID)',
        placeholder: 'Enter your QuickBooks Company ID',
        type: 'text',
        required: true,
        helperText: 'Your QuickBooks company identifier',
      },
      {
        key: 'refreshToken',
        label: 'Refresh Token',
        placeholder: 'Enter your OAuth refresh token',
        type: 'password',
        required: true,
        helperText: 'Required for maintaining connection',
      },
    ],
  },
  {
    type: IntegrationType.SEVENSHIPS,
    title: '7shifts',
    description: 'Sync employee schedules and labor data from 7shifts',
    iconName: 'schedule',
    iconColor: '#7B68EE',
    fields: [
      {
        key: 'name',
        label: 'Integration Name',
        placeholder: 'e.g., Restaurant 7shifts',
        type: 'text',
        required: true,
        helperText: 'A friendly name to identify this integration',
      },
      {
        key: 'apiKey',
        label: 'API Key',
        placeholder: 'Enter your 7shifts API key',
        type: 'password',
        required: true,
        helperText: 'Found in 7shifts under Company Settings > API',
      },
      {
        key: 'companyId',
        label: 'Company ID',
        placeholder: 'Enter your 7shifts Company ID',
        type: 'text',
        required: true,
        helperText: 'Your unique 7shifts company identifier',
      },
    ],
  },
];

export const getWidgetByType = (type: IntegrationType): IntegrationWidget | undefined => {
  return integrationWidgets.find(widget => widget.type === type);
};